nelmio_api_doc:
    documentation:
        info:
            title: Portfolio API
            description: API REST pour le portfolio
            version: 1.0.0
        servers:
            - url: http://localhost:8080
              description: Serveur de développement
    areas:
        default:
            path_patterns:
                - ^/api(?!/doc$)
    html_config:
        assets_mode: cdn
        swagger_ui_config: {}

