version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: portfolio_php
    volumes:
      - ./:/var/www/html
    networks:
      - portfolio_network
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    container_name: portfolio_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - portfolio_network
    depends_on:
      - php

  database:
    image: postgres:16-alpine
    container_name: portfolio_db
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - portfolio_network

  mailpit:
    image: axllent/mailpit
    container_name: portfolio_mailpit
    ports:
      - "8025:8025"  # Interface web
      - "1025:1025"  # SMTP
    networks:
      - portfolio_network

networks:
  portfolio_network:
    driver: bridge

volumes:
  db_data:
